### ISSUE TITLE
sshfs crashes when accessing a file

### ISSUE THREAD

**Issue by ghost** [greyltc/android_external_sshfs#1]
SSHFS Process crashes when accessing a file.

Tested on:
1. Nexus 5 - 4.4 KitKat (KRT16M) - Google Factory Image
2. Emulator - Nexus 4 - Android 4.4 - API Level 19 - armeabi-v7a

Test:
root@hammerhead:/ # sshfs user@host: /sdcard/sshfs/  
The authenticity of host 'host (192.168.xxx.xxx)' can't be established.
ECDSA key fingerprint is ...
Are you sure you want to continue connecting (yes/no)? yes
user@host's password:

root@hammerhead:/ # ps | grep ssh
root      10301 1     2628   1332  c027636c b6dc56d8 S ssh
root      10305 1     5412   228   ffffffff b6e09908 S sshfs

root@hammerhead:/ # ls /sdcard/sshfs/Downloads/test.file                                                 <
/sdcard/sshfs/Downloads/test.file

root@hammerhead:/ # cat /sdcard/sshfs/Downloads/test.file  
tmp-mksh: cat: /sdcard/sshfs/Downloads/test.file: Transport endpoint is not connected

root@hammerhead:/ # dmesg
...
<7>[ 1171.776191] SELinux: initialized (dev fuse, type fuse), uses genfs_contexts
<3>[ 1229.253004] init: untracked pid 10305 exited
<3>[ 1229.259947] init: untracked pid 10301 exited
...

**Comment by l3iggs** [comment]
Thanks for the report. I'll see if I can recreate this.

**Comment by sub77-bkp** [comment]
i have same problem at cm12. some ideas how to fix it?

**Comment by l3iggs** [comment]
I hope that 2829f966843041ec1c4454aab6ed5a7874115f53 has fixed this. Please let me know if it has.
