### ISSUE TITLE
SSHFS mounts for root, but is totally inaccessible outside of the rooted Terminal Emulator in Lollipop+

### ISSUE THREAD

**Issue by Drakonas** [greyltc/android_external_sshfs#4]
I am rewriting this issue report because I have found more details on what the problem is.

I successfully built sshfs for CM12.1-based rom. (had to rename "#include <syscall.h>" to "#include <sys/syscall.h>" in external/glib/glib/gbitlock.c to build properly for Lollipop)

Now, I used official CM12.1 source tree, but my rom is Resurrection Remix 5.1.1r2 for Moto X 2013. I'm not sure how sincere you are when you say "the source tree needs to be what your rom is built from", because my familiarity of how building things for Android differs from building for Linux is about 5%. lol. Based on my experience with Linux, I thought it'd be fine to use CM12.1 since my rom is based on it, and there is no clear guide on setting up a Resurrection Remix source tree (if that is even what you're asking for).

Anyways, it built successfully and even mounts the SSHFS properly, except there is one bug that makes the whole thing pointless... When in the root shell in Terminal Emulator, the files on my SSH server are properly read and up-to-date. The problem is that any app trying to access this folder, whether it has root access or not, sees the folder and its contents as if the mount never occurred.

Example of reproduction on Resurrection Remix (and I assume other Lollipop or CM12 based roms):

First, I created /system/sshfs with 0777 permissions.

I mounted sshfs using the exact line in your README.md to /system/sshfs.

ls -l /system/sshfs shows the files AND folders, all with 0660 permissions. Same with the /system/sshfs folder itself.

Now, if I goto /system in Root Explorer (root or non-root mode), /system/sshfs is shown to have 0777 permissions. When I go into the folder, it is empty. I can create a file there... but it does not show up in rooted Terminal Emulator, which still acts like the folder is fuse-mounted. Then, I exit to normal user mode in Terminal emulator, and presto, the folder with the file I created shows up.

If I "su -" in Terminal Emulator again, the files from my SSHFS mount are back.
###### 

It seems to me that SE Linux changes or SE context introduction in 4.4 is causing sshfs to fuse mount inside of a sandbox of some sort... which makes it inaccessible outside of the same environment that mounted it.

If you can correct any mistake I made kindly, in case it was user error on my part, please... please do so... I have wrung out my knockers trying to get working SSHFS off and on for the past year, ever since SSHFSAndroid stopped updating (which is around the time I bought it... :/ ).

**Comment by Drakonas** [comment]
Well, I figured out the issue. In the latest SuperSu, there is an option to make mountpoints sandboxed for each app that uses root, and it is enabled by default. Disabling it allows other apps to access the mount point, and there-in produces a new issue, whcich I will make a new issue for.

**Comment by l3iggs** [comment]
Nice! Does vanilla cyanogen use superSU? That's the only thing I've tested this with.

**Comment by Drakonas** [comment]
It is not included, but it is recommended by most CyanogenMod community devs to my knowledge, as it has the best support for 4.2+. I used it when testing this.
