### ISSUE TITLE
[question] Is there anything in the code that would actually prevent this running on AOSP? (nexus 6, Android 5.0.1)

### ISSUE THREAD

**Issue by wyatt8740** [greyltc/android_external_sshfs#9]
Hi, I have been porting a lot of unix-y programs to my phone recently, and I'm wondering if this uses any features that would actually _require_ a custom ROM, or if it was just developed primarily for cyanogen.

I really don't want to bother with flashing to cyanogen; I'd like to use it on my almost-stock android device. Cyanogen has a lot of stuff I don't need and/or want. I can build depended libraries, probably.

I've already compiled openSSL and gnuTLS, for example. I also think I am prepared to build glibc for it. Anything short of the kernel, basically.

**Comment by l3iggs** [comment]
I'm not sure. The first potential gotcha that comes to mind is FUSE.

Do you have [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace) available?

**Comment by wyatt8740** [comment]
I know it uses FUSE internally - I don't have any fuse-related commands, I don't think, but the internal emulated SD card is fuse mounted.

```
$ mount
/dev/fuse /mnt/shell/emulated fuse rw,nosuid,nodev,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
/dev/fuse /storage/emulated/0 fuse rw,nosuid,nodev,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
/dev/fuse /storage/emulated/legacy fuse rw,nosuid,nodev,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
```

At one point I did look at the source code for the program that mounts the SD card (it's a C program, what a pain in the butt to alter umask when it's hardcoded in), and I believe it used fuse library calls or something.

**Comment by l3iggs** [comment]
You don't have a `fusermount` command?

**Comment by wyatt8740** [comment]
Sorry for the late reply - no, I have no `fusermount` command.
